"""Generates a runnable Playwright + pytest test file from parsed Steps."""
from __future__ import annotations

from .scenario import Step

_HEADER = '''"""Auto-generated by e2e_ai.codegen — do not edit by hand.

Regenerate with:
    e2e-ai generate <scenario_file> --out <this_file>
"""
import os

from playwright.sync_api import Page, expect

BASE_URL = os.environ.get("E2E_BASE_URL", "http://localhost:5000")


'''


def _render_step(step: Step) -> list[str]:
    lines: list[str] = []
    if step.action == "visit":
        url = step.args["url"]
        lines.append(f'    page.goto(BASE_URL + "{url}")')
    elif step.action == "fill":
        field = step.args["field"]
        value = step.args["value"]
        lines.append(f'    page.get_by_label("{field}").fill("{value}")')
    elif step.action == "click":
        target = step.args["target"]
        lines.append(f'    page.get_by_role("button", name="{target}").click()')
    elif step.action == "expect_text":
        text = step.args["text"]
        lines.append(f'    expect(page.get_by_text("{text}")).to_be_visible()')
    elif step.action == "expect_url":
        url = step.args["url"]
        lines.append(f'    expect(page).to_have_url(BASE_URL + "{url}")')
    else:
        raise ValueError(f"unknown step action: {step.action}")
    return lines


def generate_test_function(name: str, steps: list[Step]) -> str:
    body_lines = []
    for step in steps:
        body_lines.extend(_render_step(step))
    body = "\n".join(body_lines)
    return f"def test_{name}(page: Page) -> None:\n{body}\n"


def generate_test_file(name: str, steps: list[Step]) -> str:
    return _HEADER + generate_test_function(name, steps)
