"""Auto-generated by e2e_ai.codegen — do not edit by hand.

Regenerate with:
    e2e-ai generate examples/login_scenario.txt --out generated_tests/test_login.py --name login
"""
import os

from playwright.sync_api import Page, expect

BASE_URL = os.environ.get("E2E_BASE_URL", "http://localhost:5000")


def test_login(page: Page) -> None:
    page.goto(BASE_URL + "/login")
    page.get_by_label("Username").fill("victoria")
    page.get_by_label("Password").fill("secret123")
    page.get_by_role("button", name="Login").click()
    expect(page.get_by_text("Welcome, victoria")).to_be_visible()
